spring:
  application:
    name: demo
  config:
    # Check import documentation:
    # https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.files.importing
    import: aws-secretsmanager:db/credentials # This imports additional configuration from secrets manager's secret
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      secretsmanager:
        reload:
          # The reload feature of Spring Cloud AWS Secrets Manager integration is able to trigger an application reload
          # when a related secret value changes.
          strategy: refresh # Only configuration beans annotated with @ConfigurationProperties or @RefreshScope are reloaded.
          period: 1m # Polling each minute
        endpoint: http://localhost:4566
        region: us-east-1
  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30  # Maximum number of connections in the connection pool
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none  # Options: none, update, create, create-drop
    show-sql: true  # Optional, logs SQL queries
    properties:
      hibernate:
        format_sql: true  # Optional, formats SQL queries for readability
    database-platform: org.hibernate.dialect.MySQLDialect  # Dialect for MySQL 8

logging:
  level:
    io.awspring.cloud: debug

management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: restart